#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --mem=125G   # memory per CPU core
#SBATCH --time=7-00:00:00
cd /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/bedtools2/bin
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.A549.biorep1.techrep1\(2\).bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams//fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.A549.biorep1.techrep1\(2\).bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.A549.biorep1.techrep2\(1\).bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams//fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.A549.biorep1.techrep2\(1\).bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.A549.biorep1.techrep3.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams//fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.A549.biorep1.techrep3.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.A549.biorep2.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams//fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.A549.biorep2.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.GM12878.biorep1.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.GM12878.biorep1.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.H1-hESC.biorep1.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.H1-hESC.biorep1.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.H1-hESC.biorep1.techrep2.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.H1-hESC.biorep1.techrep2.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.GM12878.biorep2.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.GM12878.biorep2.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HCT116.biorep1.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HCT116.biorep1.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HCT116.biorep2.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HCT116.biorep2.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HeLa-S3.biorep1.techrep2.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HeLa-S3.biorep1.techrep2.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HeLa-S3.biorep1.techrep3.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HeLa-S3.biorep1.techrep3.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HepG2.biorep2.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HepG2.biorep2.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HepG2.biorep2.techrep3.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HepG2.biorep2.techrep3.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HepG2.biorep2.techrep4.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.HepG2.biorep2.techrep4.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.IMR90.biorep1.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.IMR90.biorep1.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.IMR90.biorep1.techrep2.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.IMR90.biorep1.techrep2.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.induced_pluripotent_stem_cell.biorep2.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.induced_pluripotent_stem_cell.biorep2.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.induced_pluripotent_stem_cell.biorep2.techrep2.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.induced_pluripotent_stem_cell.biorep2.techrep2.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.induced_pluripotent_stem_cell.biorep2.techrep3.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.induced_pluripotent_stem_cell.biorep2.techrep3.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep10.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep10.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep12.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep12.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep13.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep13.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep14.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep14.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep15.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep15.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep16.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep16.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep17.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep17.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep18.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep18.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep19.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep19.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep20.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep20.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep2.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep2.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep3.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep3.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep4.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep4.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep5.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep5.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep6.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep6.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep7.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep7.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep8.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep8.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep9.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.K562.biorep2.techrep9.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.liver.biorep1.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.liver.biorep1.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.liver.biorep1.techrep2.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.liver.biorep1.techrep2.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.liver.biorep1.techrep3.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.liver.biorep1.techrep3.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.MCF-7.biorep1.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.MCF-7.biorep1.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.MCF-7.biorep1.techrep3.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.MCF-7.biorep1.techrep3.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.MCF-7.biorep1.techrep4.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.MCF-7.biorep1.techrep4.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.MCF-7.biorep1.techrep5.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.MCF-7.biorep1.techrep5.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.Panc1.biorep1.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.Panc1.biorep1.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.Panc1.biorep2.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.Panc1.biorep2.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.PC-3.biorep1.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.PC-3.biorep1.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.PC-3.biorep1.techrep2.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.PC-3.biorep1.techrep2.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.PC-3.biorep1.techrep3.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.PC-3.biorep1.techrep3.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.SK-N-SH.biorep1.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.SK-N-SH.biorep1.techrep1.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.SK-N-SH.biorep1.techrep2.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.SK-N-SH.biorep1.techrep2.bed
./bamToBed -i /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.SK-N-SH.biorep2.techrep1.bam > /fslhome/ctm34/fsl_groups/fslg_brg/compute/ENCODE_challenge/dnase-seq/bams/DNASE.SK-N-SH.biorep2.techrep1.bed

